package sqlt

import (
	"maps"

	"github.com/jackc/pgx/v5"
)

// Sanitizer formats data for safe SQL escaping.
//
// This package provides a default formatter that converts variable
// or function pipelines in the template to parameter bindings by default.
//
// Callers may define their own Sanitizers to support other functions that
// generate safe SQL and parameter mappings.
type Sanitizer interface {
	// Format must output a safe SQL string associated with an argument.
	//
	// A Sanitizer must convert any untrusted inputs into named parameters
	// and store the associated values for later retrieval via Args.
	//
	// A Template may invoke `Format` any number of times during its execution.
	Format(arg any) string

	// Args must output the collected parameter bindings associated with all
	// calls to `Format` before calling Args.
	//
	// A Template calls args after it finishes executing the template to
	// retrieve all bound parameters created in the course of template execution.
	//
	// When implementing a Sanitizer, take care that all your sanitizers use
	// non-overlapping parameter namespaces. This package reserves the `sqlt`
	// prefix as its own namespace.
	Args() pgx.NamedArgs
}

// SanitizerErr is a sanitizer that can fail.
//
// If a sanitizer is a SanitizerErr, the Template will call its Err method to
// check that execution succeeded. If one or more Sanitizers implement
// SanitizerErr and return a non-nil error, the template shall return a multierr
// combining all non-nil errors.
type SanitizerErr interface {
	Sanitizer

	// Err returns the error that occurred during formatting, or nil
	// on success.
	Err() error
}

// SanitizerFunc defines a function that returns a new instance of a Sanitizer.
//
// A Template invokes a SanitizerFunc once per execution, and the SanitizerFunc
// must return "clean" instance of the Sanitizer each time.
//
// The Template generates a new Sanitizer for each execution because the
// Sanitizer stores state related to the parameter bindings generated by the
// execution.
type SanitizerFunc func() Sanitizer

// SanitizerMap represents a binding from sanitizers to the names by which
// templates may access them.
//
// A Template doesn't automatically escape a function pipeline ending with
// a sanitizer, and assumes the sanitizer produces trusted output.
//
// This package reserves the namespace prefix `_sqlt_*` for function names.
// Callers shouldn't define functions having that prefix in a FuncMap or
// a SanitizerMap.
type SanitizerMap map[string]SanitizerFunc

// collectArgs merges the bound parameters from all sanitizers into a single
// `pgx.NamedArgs` mapping.
func collectArgs(sanitizers ...Sanitizer) pgx.NamedArgs {
	if len(sanitizers) < 1 {
		return pgx.NamedArgs{}
	}

	allArgs := make(pgx.NamedArgs)
	for _, v := range sanitizers {
		args := v.Args()
		if v == nil {
			continue
		}
		maps.Copy(allArgs, args)
	}

	return allArgs
}

type functionSanitizer[T any] struct {
	fn   func(arg T) (string, pgx.NamedArgs, error)
	args pgx.NamedArgs
	err  error
}

// Args implements [SanitizerErr].
func (f *functionSanitizer[T]) Args() pgx.NamedArgs {
	return f.args
}

// Err implements [SanitizerErr].
func (f *functionSanitizer[T]) Err() error {
	return f.err
}

// Format implements [SanitizerErr].
func (f *functionSanitizer[T]) Format(arg any) string {
	var str string
	str, f.args, f.err = f.fn(arg.(T))
	return str
}

// SanitizerF converts a single function producing a formatted string, args, and error
// into a SanitizerErr that returns a string from the Format call and saves the
// args and error. Calling Args or Err on the resulting SanitizerErr returns the
// parameter bindings and error produced by the function, respectively, if invoked
// after Format.
//
// SanitizerF uses a generic argument value to permit implementing these functions
// with strong typing.
func SanitizerF[T any](fn func(arg T) (string, pgx.NamedArgs, error)) SanitizerFunc {
	return func() Sanitizer {
		return &functionSanitizer[T]{
			fn: fn,
		}
	}
}
